name: Deploy

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    uses: ./.github/workflows/test.yml
  build:
    needs: [ test ]
    uses: ./.github/workflows/build.yml
  deploy:
    name: Deploy
    needs: [ build ]
    runs-on: ubuntu-latest

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: production
          path: ./dist

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          #github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
