name: Tests

on:
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.step1.outputs.test }}

    steps:
      - id: step1
        run: echo "test=hello" >> "$GITHUB_OUTPUT"
    
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build
        
      - name: Run Tests
        run: npm run test
        
      - name: Run Test Coverage
        id: coverage
        run: npm run coverage
